# The source of truth for these values are in tools/buildSrc/base
# Consistency is maintained via tests

baseVersion = 31.9.0
buildVersion = 8.9.0
cmdlineToolsVersion = 19.0
apiVersion = 3
nativeApiVersion = 0

lastStableBuildVersion = 8.8.1
